name: Build and Test
on: [push, workflow_dispatch]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        racket-variant: ['CS']
        racket-version: ['8.6', '8.10', '8.14', '8.18', 'stable', 'current']
    runs-on: ${{ matrix.os }}
    name: OS ${{ matrix.os }} / Racket ${{ matrix.racket-version }}

    steps:

    - name: Checkout
      uses: actions/checkout@main

    - name: Install Racket
      uses: Bogdanp/setup-racket@v1.14
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: ${{ matrix.racket-variant }}
        version: ${{ matrix.racket-version }}

    - name: Install LLVM
      uses: egor-tensin/setup-clang@v2
      with:
        version: latest
        platform: x64

    - name: Install libssl
      run: |
        sudo apt install -y libssl-dev

    - name: Version info
      run: |
        clang --version
        gcc --version

    - name: Install a86 package
      run: |
        raco pkg install --no-docs ../a86/

    - name: Install langs package
      run: |
        # This *should* use the locally installed a86
        raco pkg install --auto 'https://github.com/cmsc430/langs.git?#main'

    - name: Run tests
      run: |
        xvfb-run raco test -p a86
        xvfb-run raco test -p langs
